# Generated by Django 5.2.5 on 2025-12-19 19:56

import os
import urllib.request
from django.db import migrations
from django.core.files.base import ContentFile


def download_images(apps, schema_editor):
    Product = apps.get_model('nikeapp', 'Product')
    for product in Product.objects.filter(image__isnull=False).exclude(image=''):
        image_url = product.image.name if hasattr(product.image, 'name') else str(product.image)
        if image_url.startswith('http'):
            try:
                # Download the image
                with urllib.request.urlopen(image_url) as response:
                    image_data = response.read()
                
                # Create filename
                filename = f"{product.slug}.png"
                
                # Save the image
                product.image.save(filename, ContentFile(image_data), save=True)
                print(f"Downloaded image for {product.name}")
            except Exception as e:
                print(f"Failed to download image for {product.name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('nikeapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RunPython(download_images),
    ]
