# Generated by Django 6.0 on 2025-12-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikeapp', '0004_auto_20251220_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
