# Generated by Django 5.2.5 on 2025-12-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikeapp', '0005_order_stripe_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_id',
        ),
    ]
